import vortexFormat from "@vortexnyc/tooling/oxfmt";
import vortexLint from "@vortexnyc/tooling/oxlint";
import { defineConfig } from "vite-plus";

// Generated by @vortexnyc/tooling vortex-project-kit. Edit the shared policies, not this file.

export default defineConfig({
  fmt: vortexFormat,
  lint: vortexLint,
  staged: {
    "*.{js,jsx,ts,tsx}": ["vp lint --fix", "vp fmt"],
    "*.{css,json,jsonc}": "vp fmt",
  },
});
