import { defineConfig } from "vite-plus";

const fmt = {
  arrowParens: "always" as const,
  bracketSameLine: false,
  bracketSpacing: true,
  endOfLine: "lf" as const,
  jsxSingleQuote: false,
  printWidth: 80,
  quoteProps: "as-needed" as const,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5" as const,
  useTabs: false,
  sortImports: { ignoreCase: true, newlinesBetween: true, order: "asc" },
  sortPackageJson: true,
  proseWrap: "preserve" as const,
  sortTailwindcss: {
    functions: ["cn", "cva", "clsx", "twMerge", "tw"],
  },
  ignorePatterns: [
    "packages/documents/vendor/extend-ui/**",
    "**/vendor/**",
    "renovate.json",
    "lefthook.yml",
    "LLM-INTEGRATION.md",
    ".github/workflows/vortex-quality.yml",
    ".github/workflows/vortex-main-proof.yml",
    "**/node_modules",
    "**/dist",
    "**/build",
    "**/out",
    "**/coverage",
    "**/.turbo",
    "**/.wrangler",
    "**/.astro",
    "**/_astro",
    "**/.vercel",
    "**/.netlify",
    "**/.cache",
    "**/.vite",
    "**/.expo",
    "**/.expo-shared",
    "**/_generated",
    "**/generated",
    "**/__generated__",
    "**/*.gen.*",
    "**/*.generated.*",
    "**/bun.lock",
    "**/bun.lockb",
    "**/pnpm-lock.yaml",
    "**/pnpm-workspace.yaml",
    "**/package-lock.json",
    "**/yarn.lock",
  ],
};

export default defineConfig({
  fmt,
  lint: {},
  staged: {
    "*.{js,jsx,ts,tsx}": ["vp lint --fix", "vp fmt"],
    "*.{css,json,jsonc}": "vp fmt",
  },
});
