name = "seal-site-dev"
main = "src/worker.ts"
compatibility_date = "2026-09-16"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
workers_dev = false
preview_urls = false

[observability]
enabled = true
logs = { enabled = true }
traces = { enabled = true, head_sampling_rate = 0.1 }

[[d1_databases]]
binding = "DB"
database_name = "seal-site-dev"
database_id = "c78f16c2-9965-483f-bbb1-5ee56881218d"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "seal-site-media-dev"

[[kv_namespaces]]
binding = "CACHE"
id = "c3e1eedd1533466b8f589aed4d2e010e"

[[worker_loaders]]
binding = "LOADER"

[triggers]
crons = ["* * * * *"]

[env.production]
name = "seal-site"
workers_dev = false
preview_urls = true

[env.production.observability]
enabled = true
logs = { enabled = true }
traces = { enabled = true, head_sampling_rate = 0.1 }

[[env.production.d1_databases]]
binding = "DB"
database_name = "seal-site"
database_id = "98724613-82fc-44c7-b40d-d07a99da68a0"

[[env.production.r2_buckets]]
binding = "MEDIA"
bucket_name = "seal-site-media"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "9f7b0df19b0e409da75d20edf089836c"

[[env.production.worker_loaders]]
binding = "LOADER"

[env.production.triggers]
crons = ["* * * * *"]

[[env.production.routes]]
pattern = "seal.nyc"
custom_domain = true

[[env.production.routes]]
pattern = "www.seal.nyc"
custom_domain = true
