/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthAcceptInviteRouteImport } from './routes/_auth/accept-invite'
import { Route as AuthenticatedSlugIndexRouteImport } from './routes/_authenticated/$slug/index'
import { Route as AuthenticatedSlugTemplatesRouteImport } from './routes/_authenticated/$slug/templates'
import { Route as AuthenticatedSlugHomeRouteImport } from './routes/_authenticated/$slug/home'
import { Route as AuthenticatedSlugDocumentsRouteImport } from './routes/_authenticated/$slug/documents'
import { Route as AuthenticatedSlugAnalyticsRouteImport } from './routes/_authenticated/$slug/analytics'
import { Route as AuthenticatedOnboardingChooseOrganizationIndexRouteImport } from './routes/_authenticated/onboarding/choose-organization/index'
import { Route as AuthenticatedSlugSettingsIndexRouteImport } from './routes/_authenticated/$slug/settings/index'
import { Route as AuthenticatedSlugSettingsTeamRouteImport } from './routes/_authenticated/$slug/settings/team'
import { Route as AuthenticatedSlugSettingsProfileRouteImport } from './routes/_authenticated/$slug/settings/profile'
import { Route as AuthenticatedSlugSettingsBillingRouteImport } from './routes/_authenticated/$slug/settings/billing'
import { Route as AuthenticatedSlugDocumentsDocumentIdRouteImport } from './routes/_authenticated/$slug/documents/$documentId'
import { Route as AuthenticatedSlugSettingsTeamIndexRouteImport } from './routes/_authenticated/$slug/settings/team/index'
import { Route as AuthenticatedSlugSettingsProfileIndexRouteImport } from './routes/_authenticated/$slug/settings/profile/index'
import { Route as AuthenticatedSlugSettingsTeamMemberIdRouteImport } from './routes/_authenticated/$slug/settings/team/$memberId'
import { Route as AuthenticatedSlugSettingsProfileUsageRouteImport } from './routes/_authenticated/$slug/settings/profile/usage'
import { Route as AuthenticatedSlugSettingsProfileSecurityRouteImport } from './routes/_authenticated/$slug/settings/profile/security'
import { Route as AuthenticatedSlugSettingsProfileNotificationsRouteImport } from './routes/_authenticated/$slug/settings/profile/notifications'
import { Route as AuthenticatedSlugSettingsProfileIntegrationsRouteImport } from './routes/_authenticated/$slug/settings/profile/integrations'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSlugIndexRoute = AuthenticatedSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugTemplatesRoute =
  AuthenticatedSlugTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugHomeRoute = AuthenticatedSlugHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedSlugDocumentsRoute =
  AuthenticatedSlugDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugAnalyticsRoute =
  AuthenticatedSlugAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedOnboardingChooseOrganizationIndexRoute =
  AuthenticatedOnboardingChooseOrganizationIndexRouteImport.update({
    id: '/onboarding/choose-organization/',
    path: '/onboarding/choose-organization/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSlugSettingsIndexRoute =
  AuthenticatedSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsTeamRoute =
  AuthenticatedSlugSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsProfileRoute =
  AuthenticatedSlugSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugSettingsBillingRoute =
  AuthenticatedSlugSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugDocumentsDocumentIdRoute =
  AuthenticatedSlugDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedSlugDocumentsRoute,
  } as any)
const AuthenticatedSlugSettingsTeamIndexRoute =
  AuthenticatedSlugSettingsTeamIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugSettingsTeamRoute,
  } as any)
const AuthenticatedSlugSettingsProfileIndexRoute =
  AuthenticatedSlugSettingsProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugSettingsProfileRoute,
  } as any)
const AuthenticatedSlugSettingsTeamMemberIdRoute =
  AuthenticatedSlugSettingsTeamMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedSlugSettingsTeamRoute,
  } as any)
const AuthenticatedSlugSettingsProfileUsageRoute =
  AuthenticatedSlugSettingsProfileUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedSlugSettingsProfileRoute,
  } as any)
const AuthenticatedSlugSettingsProfileSecurityRoute =
  AuthenticatedSlugSettingsProfileSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSlugSettingsProfileRoute,
  } as any)
const AuthenticatedSlugSettingsProfileNotificationsRoute =
  AuthenticatedSlugSettingsProfileNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSlugSettingsProfileRoute,
  } as any)
const AuthenticatedSlugSettingsProfileIntegrationsRoute =
  AuthenticatedSlugSettingsProfileIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSlugSettingsProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/$slug/analytics': typeof AuthenticatedSlugAnalyticsRoute
  '/$slug/documents': typeof AuthenticatedSlugDocumentsRouteWithChildren
  '/$slug/home': typeof AuthenticatedSlugHomeRoute
  '/$slug/templates': typeof AuthenticatedSlugTemplatesRoute
  '/$slug/': typeof AuthenticatedSlugIndexRoute
  '/$slug/documents/$documentId': typeof AuthenticatedSlugDocumentsDocumentIdRoute
  '/$slug/settings/billing': typeof AuthenticatedSlugSettingsBillingRoute
  '/$slug/settings/profile': typeof AuthenticatedSlugSettingsProfileRouteWithChildren
  '/$slug/settings/team': typeof AuthenticatedSlugSettingsTeamRouteWithChildren
  '/$slug/settings': typeof AuthenticatedSlugSettingsIndexRoute
  '/onboarding/choose-organization': typeof AuthenticatedOnboardingChooseOrganizationIndexRoute
  '/$slug/settings/profile/integrations': typeof AuthenticatedSlugSettingsProfileIntegrationsRoute
  '/$slug/settings/profile/notifications': typeof AuthenticatedSlugSettingsProfileNotificationsRoute
  '/$slug/settings/profile/security': typeof AuthenticatedSlugSettingsProfileSecurityRoute
  '/$slug/settings/profile/usage': typeof AuthenticatedSlugSettingsProfileUsageRoute
  '/$slug/settings/team/$memberId': typeof AuthenticatedSlugSettingsTeamMemberIdRoute
  '/$slug/settings/profile/': typeof AuthenticatedSlugSettingsProfileIndexRoute
  '/$slug/settings/team/': typeof AuthenticatedSlugSettingsTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/accept-invite': typeof AuthAcceptInviteRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$slug/analytics': typeof AuthenticatedSlugAnalyticsRoute
  '/$slug/documents': typeof AuthenticatedSlugDocumentsRouteWithChildren
  '/$slug/home': typeof AuthenticatedSlugHomeRoute
  '/$slug/templates': typeof AuthenticatedSlugTemplatesRoute
  '/$slug': typeof AuthenticatedSlugIndexRoute
  '/$slug/documents/$documentId': typeof AuthenticatedSlugDocumentsDocumentIdRoute
  '/$slug/settings/billing': typeof AuthenticatedSlugSettingsBillingRoute
  '/$slug/settings': typeof AuthenticatedSlugSettingsIndexRoute
  '/onboarding/choose-organization': typeof AuthenticatedOnboardingChooseOrganizationIndexRoute
  '/$slug/settings/profile/integrations': typeof AuthenticatedSlugSettingsProfileIntegrationsRoute
  '/$slug/settings/profile/notifications': typeof AuthenticatedSlugSettingsProfileNotificationsRoute
  '/$slug/settings/profile/security': typeof AuthenticatedSlugSettingsProfileSecurityRoute
  '/$slug/settings/profile/usage': typeof AuthenticatedSlugSettingsProfileUsageRoute
  '/$slug/settings/team/$memberId': typeof AuthenticatedSlugSettingsTeamMemberIdRoute
  '/$slug/settings/profile': typeof AuthenticatedSlugSettingsProfileIndexRoute
  '/$slug/settings/team': typeof AuthenticatedSlugSettingsTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/app': typeof AppRoute
  '/_auth/accept-invite': typeof AuthAcceptInviteRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/_authenticated/$slug/analytics': typeof AuthenticatedSlugAnalyticsRoute
  '/_authenticated/$slug/documents': typeof AuthenticatedSlugDocumentsRouteWithChildren
  '/_authenticated/$slug/home': typeof AuthenticatedSlugHomeRoute
  '/_authenticated/$slug/templates': typeof AuthenticatedSlugTemplatesRoute
  '/_authenticated/$slug/': typeof AuthenticatedSlugIndexRoute
  '/_authenticated/$slug/documents/$documentId': typeof AuthenticatedSlugDocumentsDocumentIdRoute
  '/_authenticated/$slug/settings/billing': typeof AuthenticatedSlugSettingsBillingRoute
  '/_authenticated/$slug/settings/profile': typeof AuthenticatedSlugSettingsProfileRouteWithChildren
  '/_authenticated/$slug/settings/team': typeof AuthenticatedSlugSettingsTeamRouteWithChildren
  '/_authenticated/$slug/settings/': typeof AuthenticatedSlugSettingsIndexRoute
  '/_authenticated/onboarding/choose-organization/': typeof AuthenticatedOnboardingChooseOrganizationIndexRoute
  '/_authenticated/$slug/settings/profile/integrations': typeof AuthenticatedSlugSettingsProfileIntegrationsRoute
  '/_authenticated/$slug/settings/profile/notifications': typeof AuthenticatedSlugSettingsProfileNotificationsRoute
  '/_authenticated/$slug/settings/profile/security': typeof AuthenticatedSlugSettingsProfileSecurityRoute
  '/_authenticated/$slug/settings/profile/usage': typeof AuthenticatedSlugSettingsProfileUsageRoute
  '/_authenticated/$slug/settings/team/$memberId': typeof AuthenticatedSlugSettingsTeamMemberIdRoute
  '/_authenticated/$slug/settings/profile/': typeof AuthenticatedSlugSettingsProfileIndexRoute
  '/_authenticated/$slug/settings/team/': typeof AuthenticatedSlugSettingsTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/accept-invite'
    | '/sign-in'
    | '/sign-up'
    | '/$slug'
    | '/$slug/analytics'
    | '/$slug/documents'
    | '/$slug/home'
    | '/$slug/templates'
    | '/$slug/'
    | '/$slug/documents/$documentId'
    | '/$slug/settings/billing'
    | '/$slug/settings/profile'
    | '/$slug/settings/team'
    | '/$slug/settings'
    | '/onboarding/choose-organization'
    | '/$slug/settings/profile/integrations'
    | '/$slug/settings/profile/notifications'
    | '/$slug/settings/profile/security'
    | '/$slug/settings/profile/usage'
    | '/$slug/settings/team/$memberId'
    | '/$slug/settings/profile/'
    | '/$slug/settings/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/accept-invite'
    | '/sign-in'
    | '/sign-up'
    | '/$slug/analytics'
    | '/$slug/documents'
    | '/$slug/home'
    | '/$slug/templates'
    | '/$slug'
    | '/$slug/documents/$documentId'
    | '/$slug/settings/billing'
    | '/$slug/settings'
    | '/onboarding/choose-organization'
    | '/$slug/settings/profile/integrations'
    | '/$slug/settings/profile/notifications'
    | '/$slug/settings/profile/security'
    | '/$slug/settings/profile/usage'
    | '/$slug/settings/team/$memberId'
    | '/$slug/settings/profile'
    | '/$slug/settings/team'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/app'
    | '/_auth/accept-invite'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_authenticated/$slug'
    | '/_authenticated/$slug/analytics'
    | '/_authenticated/$slug/documents'
    | '/_authenticated/$slug/home'
    | '/_authenticated/$slug/templates'
    | '/_authenticated/$slug/'
    | '/_authenticated/$slug/documents/$documentId'
    | '/_authenticated/$slug/settings/billing'
    | '/_authenticated/$slug/settings/profile'
    | '/_authenticated/$slug/settings/team'
    | '/_authenticated/$slug/settings/'
    | '/_authenticated/onboarding/choose-organization/'
    | '/_authenticated/$slug/settings/profile/integrations'
    | '/_authenticated/$slug/settings/profile/notifications'
    | '/_authenticated/$slug/settings/profile/security'
    | '/_authenticated/$slug/settings/profile/usage'
    | '/_authenticated/$slug/settings/team/$memberId'
    | '/_authenticated/$slug/settings/profile/'
    | '/_authenticated/$slug/settings/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AppRoute: typeof AppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accept-invite': {
      id: '/_auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/$slug/': {
      id: '/_authenticated/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthenticatedSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/templates': {
      id: '/_authenticated/$slug/templates'
      path: '/templates'
      fullPath: '/$slug/templates'
      preLoaderRoute: typeof AuthenticatedSlugTemplatesRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/home': {
      id: '/_authenticated/$slug/home'
      path: '/home'
      fullPath: '/$slug/home'
      preLoaderRoute: typeof AuthenticatedSlugHomeRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/documents': {
      id: '/_authenticated/$slug/documents'
      path: '/documents'
      fullPath: '/$slug/documents'
      preLoaderRoute: typeof AuthenticatedSlugDocumentsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/analytics': {
      id: '/_authenticated/$slug/analytics'
      path: '/analytics'
      fullPath: '/$slug/analytics'
      preLoaderRoute: typeof AuthenticatedSlugAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/onboarding/choose-organization/': {
      id: '/_authenticated/onboarding/choose-organization/'
      path: '/onboarding/choose-organization'
      fullPath: '/onboarding/choose-organization'
      preLoaderRoute: typeof AuthenticatedOnboardingChooseOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug/settings/': {
      id: '/_authenticated/$slug/settings/'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof AuthenticatedSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/team': {
      id: '/_authenticated/$slug/settings/team'
      path: '/settings/team'
      fullPath: '/$slug/settings/team'
      preLoaderRoute: typeof AuthenticatedSlugSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/profile': {
      id: '/_authenticated/$slug/settings/profile'
      path: '/settings/profile'
      fullPath: '/$slug/settings/profile'
      preLoaderRoute: typeof AuthenticatedSlugSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/settings/billing': {
      id: '/_authenticated/$slug/settings/billing'
      path: '/settings/billing'
      fullPath: '/$slug/settings/billing'
      preLoaderRoute: typeof AuthenticatedSlugSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/documents/$documentId': {
      id: '/_authenticated/$slug/documents/$documentId'
      path: '/$documentId'
      fullPath: '/$slug/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedSlugDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedSlugDocumentsRoute
    }
    '/_authenticated/$slug/settings/team/': {
      id: '/_authenticated/$slug/settings/team/'
      path: '/'
      fullPath: '/$slug/settings/team/'
      preLoaderRoute: typeof AuthenticatedSlugSettingsTeamIndexRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsTeamRoute
    }
    '/_authenticated/$slug/settings/profile/': {
      id: '/_authenticated/$slug/settings/profile/'
      path: '/'
      fullPath: '/$slug/settings/profile/'
      preLoaderRoute: typeof AuthenticatedSlugSettingsProfileIndexRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsProfileRoute
    }
    '/_authenticated/$slug/settings/team/$memberId': {
      id: '/_authenticated/$slug/settings/team/$memberId'
      path: '/$memberId'
      fullPath: '/$slug/settings/team/$memberId'
      preLoaderRoute: typeof AuthenticatedSlugSettingsTeamMemberIdRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsTeamRoute
    }
    '/_authenticated/$slug/settings/profile/usage': {
      id: '/_authenticated/$slug/settings/profile/usage'
      path: '/usage'
      fullPath: '/$slug/settings/profile/usage'
      preLoaderRoute: typeof AuthenticatedSlugSettingsProfileUsageRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsProfileRoute
    }
    '/_authenticated/$slug/settings/profile/security': {
      id: '/_authenticated/$slug/settings/profile/security'
      path: '/security'
      fullPath: '/$slug/settings/profile/security'
      preLoaderRoute: typeof AuthenticatedSlugSettingsProfileSecurityRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsProfileRoute
    }
    '/_authenticated/$slug/settings/profile/notifications': {
      id: '/_authenticated/$slug/settings/profile/notifications'
      path: '/notifications'
      fullPath: '/$slug/settings/profile/notifications'
      preLoaderRoute: typeof AuthenticatedSlugSettingsProfileNotificationsRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsProfileRoute
    }
    '/_authenticated/$slug/settings/profile/integrations': {
      id: '/_authenticated/$slug/settings/profile/integrations'
      path: '/integrations'
      fullPath: '/$slug/settings/profile/integrations'
      preLoaderRoute: typeof AuthenticatedSlugSettingsProfileIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSlugSettingsProfileRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedSlugDocumentsRouteChildren {
  AuthenticatedSlugDocumentsDocumentIdRoute: typeof AuthenticatedSlugDocumentsDocumentIdRoute
}

const AuthenticatedSlugDocumentsRouteChildren: AuthenticatedSlugDocumentsRouteChildren =
  {
    AuthenticatedSlugDocumentsDocumentIdRoute:
      AuthenticatedSlugDocumentsDocumentIdRoute,
  }

const AuthenticatedSlugDocumentsRouteWithChildren =
  AuthenticatedSlugDocumentsRoute._addFileChildren(
    AuthenticatedSlugDocumentsRouteChildren,
  )

interface AuthenticatedSlugSettingsProfileRouteChildren {
  AuthenticatedSlugSettingsProfileIntegrationsRoute: typeof AuthenticatedSlugSettingsProfileIntegrationsRoute
  AuthenticatedSlugSettingsProfileNotificationsRoute: typeof AuthenticatedSlugSettingsProfileNotificationsRoute
  AuthenticatedSlugSettingsProfileSecurityRoute: typeof AuthenticatedSlugSettingsProfileSecurityRoute
  AuthenticatedSlugSettingsProfileUsageRoute: typeof AuthenticatedSlugSettingsProfileUsageRoute
  AuthenticatedSlugSettingsProfileIndexRoute: typeof AuthenticatedSlugSettingsProfileIndexRoute
}

const AuthenticatedSlugSettingsProfileRouteChildren: AuthenticatedSlugSettingsProfileRouteChildren =
  {
    AuthenticatedSlugSettingsProfileIntegrationsRoute:
      AuthenticatedSlugSettingsProfileIntegrationsRoute,
    AuthenticatedSlugSettingsProfileNotificationsRoute:
      AuthenticatedSlugSettingsProfileNotificationsRoute,
    AuthenticatedSlugSettingsProfileSecurityRoute:
      AuthenticatedSlugSettingsProfileSecurityRoute,
    AuthenticatedSlugSettingsProfileUsageRoute:
      AuthenticatedSlugSettingsProfileUsageRoute,
    AuthenticatedSlugSettingsProfileIndexRoute:
      AuthenticatedSlugSettingsProfileIndexRoute,
  }

const AuthenticatedSlugSettingsProfileRouteWithChildren =
  AuthenticatedSlugSettingsProfileRoute._addFileChildren(
    AuthenticatedSlugSettingsProfileRouteChildren,
  )

interface AuthenticatedSlugSettingsTeamRouteChildren {
  AuthenticatedSlugSettingsTeamMemberIdRoute: typeof AuthenticatedSlugSettingsTeamMemberIdRoute
  AuthenticatedSlugSettingsTeamIndexRoute: typeof AuthenticatedSlugSettingsTeamIndexRoute
}

const AuthenticatedSlugSettingsTeamRouteChildren: AuthenticatedSlugSettingsTeamRouteChildren =
  {
    AuthenticatedSlugSettingsTeamMemberIdRoute:
      AuthenticatedSlugSettingsTeamMemberIdRoute,
    AuthenticatedSlugSettingsTeamIndexRoute:
      AuthenticatedSlugSettingsTeamIndexRoute,
  }

const AuthenticatedSlugSettingsTeamRouteWithChildren =
  AuthenticatedSlugSettingsTeamRoute._addFileChildren(
    AuthenticatedSlugSettingsTeamRouteChildren,
  )

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugAnalyticsRoute: typeof AuthenticatedSlugAnalyticsRoute
  AuthenticatedSlugDocumentsRoute: typeof AuthenticatedSlugDocumentsRouteWithChildren
  AuthenticatedSlugHomeRoute: typeof AuthenticatedSlugHomeRoute
  AuthenticatedSlugTemplatesRoute: typeof AuthenticatedSlugTemplatesRoute
  AuthenticatedSlugIndexRoute: typeof AuthenticatedSlugIndexRoute
  AuthenticatedSlugSettingsBillingRoute: typeof AuthenticatedSlugSettingsBillingRoute
  AuthenticatedSlugSettingsProfileRoute: typeof AuthenticatedSlugSettingsProfileRouteWithChildren
  AuthenticatedSlugSettingsTeamRoute: typeof AuthenticatedSlugSettingsTeamRouteWithChildren
  AuthenticatedSlugSettingsIndexRoute: typeof AuthenticatedSlugSettingsIndexRoute
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugAnalyticsRoute: AuthenticatedSlugAnalyticsRoute,
  AuthenticatedSlugDocumentsRoute: AuthenticatedSlugDocumentsRouteWithChildren,
  AuthenticatedSlugHomeRoute: AuthenticatedSlugHomeRoute,
  AuthenticatedSlugTemplatesRoute: AuthenticatedSlugTemplatesRoute,
  AuthenticatedSlugIndexRoute: AuthenticatedSlugIndexRoute,
  AuthenticatedSlugSettingsBillingRoute: AuthenticatedSlugSettingsBillingRoute,
  AuthenticatedSlugSettingsProfileRoute:
    AuthenticatedSlugSettingsProfileRouteWithChildren,
  AuthenticatedSlugSettingsTeamRoute:
    AuthenticatedSlugSettingsTeamRouteWithChildren,
  AuthenticatedSlugSettingsIndexRoute: AuthenticatedSlugSettingsIndexRoute,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
  AuthenticatedOnboardingChooseOrganizationIndexRoute: typeof AuthenticatedOnboardingChooseOrganizationIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
  AuthenticatedOnboardingChooseOrganizationIndexRoute:
    AuthenticatedOnboardingChooseOrganizationIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AppRoute: AppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
