import type { VortexSurfaceDefinition } from "./types";

export const VORTEX_PAYMENTS_SURFACES = [
  {
    id: "checkout",
    label: "VortexCheckout",
    mode: "hosted_redirect",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-hosted-link-launcher",
  },
  {
    id: "embedded_checkout",
    label: "VortexEmbeddedCheckout",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-embedded-checkout",
  },
  {
    id: "promo_code_control",
    label: "VortexPromoCodeControl",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-promo-code-control",
  },
  {
    id: "balance_wallet_panel",
    label: "VortexBalanceWalletPanel",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-balance-wallet-panel",
  },
  {
    id: "recovery_summary",
    label: "VortexRecoverySummary",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-recovery-summary",
  },
  {
    id: "entitlement_summary",
    label: "VortexEntitlementSummary",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-entitlement-summary",
  },
  {
    id: "payment_timeline_summary",
    label: "VortexPaymentTimelineSummary",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-payment-timeline-summary",
  },
  {
    id: "billing_status_banner",
    label: "VortexBillingStatusBanner",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-billing-status-banner",
  },
  {
    id: "subscription_action_summary",
    label: "VortexSubscriptionActionSummary",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-subscription-action-summary",
  },
  {
    id: "payment_method_summary",
    label: "VortexPaymentMethodSummary",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-payment-method-summary",
  },
  {
    id: "invoice_list",
    label: "VortexInvoiceList",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-invoice-list",
  },
  {
    id: "plan_comparison",
    label: "VortexPlanComparison",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-plan-comparison",
  },
  {
    id: "usage_meter_summary",
    label: "VortexUsageMeterSummary",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-usage-meter-summary",
  },
  {
    id: "receipt_download_button",
    label: "VortexReceiptDownloadButton",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-receipt-download-button",
  },
  {
    id: "merchant_onboarding",
    label: "VortexMerchantOnboarding",
    mode: "hosted_redirect",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-merchant-onboarding-surface",
  },
  {
    id: "pay_link",
    label: "VortexPayLink",
    mode: "hosted_redirect",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-pay-link-surface",
  },
  {
    id: "customer_portal",
    label: "VortexCustomerPortal",
    mode: "hosted_redirect",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-customer-portal-surface",
  },
  {
    id: "payment_methods",
    label: "VortexPaymentMethods",
    mode: "hosted_redirect",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-customer-portal-surface",
  },
  {
    id: "payment_recovery",
    label: "VortexPaymentRecovery",
    mode: "hosted_redirect",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-payment-recovery-surface",
  },
  {
    id: "subscription_manager",
    label: "VortexSubscriptionManager",
    mode: "hosted_redirect",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-customer-portal-surface",
  },
  {
    id: "invoice_receipt_center",
    label: "VortexInvoiceReceiptCenter",
    mode: "hosted_redirect",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-invoice-receipt-center",
  },
  {
    id: "merchant_ops_dashboard",
    label: "VortexMerchantOpsDashboard",
    mode: "operator_console",
    status: "operator_only",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-merchant-ops-dashboard",
  },
  {
    id: "collections_queue",
    label: "VortexCollectionsQueue",
    mode: "operator_console",
    status: "operator_only",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-collections-queue-surface",
  },
  {
    id: "billing_inspector",
    label: "VortexBillingInspector",
    mode: "operator_console",
    status: "operator_only",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-billing-inspector-surface",
  },
  {
    id: "merchant_account_panel",
    label: "VortexMerchantAccountPanel",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-merchant-account-panel",
  },
  {
    id: "payout_readiness",
    label: "VortexPayoutReadinessPanel",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-payout-readiness-surface",
  },
  {
    id: "fee_policy_panel",
    label: "VortexFeePolicyPanel",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-fee-policy-panel",
  },
  {
    id: "merchant_action_queue",
    label: "VortexMerchantActionQueue",
    mode: "embedded_component",
    status: "proved",
    packageExport: "@vortex/payments/react",
    proofTarget: "prove:vortex-merchant-action-queue",
  },
] as const satisfies readonly VortexSurfaceDefinition[];
