/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ChangelogSlugRouteImport } from './routes/changelog.$slug'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChangelogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/studio': typeof StudioRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/pages/$slug': typeof PagesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/studio': typeof StudioRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/pages/$slug': typeof PagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/studio': typeof StudioRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/pages/$slug': typeof PagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/docs'
    | '/privacy-policy'
    | '/studio'
    | '/terms-of-service'
    | '/changelog/$slug'
    | '/docs/$'
    | '/pages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/docs'
    | '/privacy-policy'
    | '/studio'
    | '/terms-of-service'
    | '/changelog/$slug'
    | '/docs/$'
    | '/pages/$slug'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/docs'
    | '/privacy-policy'
    | '/studio'
    | '/terms-of-service'
    | '/changelog/$slug'
    | '/docs/$'
    | '/pages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  StudioRoute: typeof StudioRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  PagesSlugRoute: typeof PagesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof ChangelogRoute
    }
  }
}

interface ChangelogRouteChildren {
  ChangelogSlugRoute: typeof ChangelogSlugRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogSlugRoute: ChangelogSlugRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  StudioRoute: StudioRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  PagesSlugRoute: PagesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
