/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ChangelogSlugRouteImport } from './routes/changelog.$slug'
import { Route as DeveloperSplatRouteImport } from './routes/developer/$'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChangelogRoute,
} as any)
const DeveloperSplatRoute = DeveloperSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DeveloperRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/compare': typeof CompareRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/developer/$': typeof DeveloperSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/pages/$slug': typeof PagesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/compare': typeof CompareRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/developer/$': typeof DeveloperSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/pages/$slug': typeof PagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRouteWithChildren
  '/compare': typeof CompareRoute
  '/developer': typeof DeveloperRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/developer/$': typeof DeveloperSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/pages/$slug': typeof PagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/compare'
    | '/developer'
    | '/docs'
    | '/integrations'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/changelog/$slug'
    | '/developer/$'
    | '/docs/$'
    | '/pages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/compare'
    | '/developer'
    | '/docs'
    | '/integrations'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/changelog/$slug'
    | '/developer/$'
    | '/docs/$'
    | '/pages/$slug'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/compare'
    | '/developer'
    | '/docs'
    | '/integrations'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/changelog/$slug'
    | '/developer/$'
    | '/docs/$'
    | '/pages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRouteWithChildren
  CompareRoute: typeof CompareRoute
  DeveloperRoute: typeof DeveloperRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  PagesSlugRoute: typeof PagesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/developer/$': {
      id: '/developer/$'
      path: '/$'
      fullPath: '/developer/$'
      preLoaderRoute: typeof DeveloperSplatRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChangelogRouteChildren {
  ChangelogSlugRoute: typeof ChangelogSlugRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogSlugRoute: ChangelogSlugRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

interface DeveloperRouteChildren {
  DeveloperSplatRoute: typeof DeveloperSplatRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperSplatRoute: DeveloperSplatRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRouteWithChildren,
  CompareRoute: CompareRoute,
  DeveloperRoute: DeveloperRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  PagesSlugRoute: PagesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
