#!/usr/bin/env bun

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const repoRoot = new URL("..", import.meta.url).pathname;
const retiredProviderToken = String.fromCharCode(115, 116, 114, 105, 112, 101);
const retiredProviderContentPattern = `\\b${retiredProviderToken}\\b|@${retiredProviderToken}/|${retiredProviderToken}[_-]`;
const retiredProviderContentRegex = new RegExp(
  retiredProviderContentPattern,
  "i"
);
const activeConfigExamplePaths = [
  ".env.example",
  ".test-env.example",
  "apps/backend/.env.example",
  "apps/web/.env.example",
  "apps/landing/.env.example",
] as const;
const activeGuidanceAndConfigPaths = [
  ...activeConfigExamplePaths,
  // AGENTS.md is generated by @vortexnyc/tooling project-kit (drift-gated), and its Core-owned
  // money/provider doctrine cites the retired provider as an external comparison standard.
  // Seal cannot reword it, so it is exempt here; all other guidance stays strictly scanned.
  "CLAUDE.md",
  "LLM-INTEGRATION.md",
  "README.md",
  "docs/plans/2026-07-07-legacy-provider-to-vortex-top-down-migration.md",
  "goal.md",
  "turbo.json",
  "vortex.project.json",
] as const;
const activeVortexMirrorSchemaPaths = [
  "apps/backend/convex/schemas/subscription_coupons.ts",
  "apps/backend/convex/schemas/subscription_promo_codes.ts",
] as const;
const retiredProviderAliasRegex =
  /\bretired provider\b|retired-provider|retired_provider|RETIRED_PROVIDER/i;
const allowedRetiredProviderCommandNames = [
  "prove:zero-retired-provider-residue",
  "prove-zero-retired-provider-residue",
] as const;
const stalePaymentProviderMirrorRegex = /\bpayment provider\b/i;
const generatedOrInstalledDirectoryNames = new Set([
  ".git",
  "node_modules",
  ".cache",
  ".turbo",
  ".openlogs",
  ".playwright-mcp",
  ".playwright-cli",
  ".playwright-profile",
  ".source",
  ".vite",
  ".vite-content-tools",
  ".nitro",
  ".output",
  "dist",
  "playwright-report",
  "test-results",
  "coverage",
]);

const trackedFiles = execFileSync("git", ["ls-files", "-z"], {
  cwd: repoRoot,
  encoding: "utf8",
})
  .split("\0")
  .filter((path) => path.length > 0);

const failures: string[] = [];

const lockfileContents = readFileSync(join(repoRoot, "pnpm-lock.yaml"), "utf8");
if (
  new RegExp(String.raw`[@/'"]${retiredProviderToken}\b`, "i").test(
    lockfileContents
  )
) {
  failures.push(
    "pnpm-lock.yaml: dependency graph contains retired provider package"
  );
}

// Pure-Node working-tree scan (hidden + untracked included). CI runners are
// ephemeral clean machines with no ripgrep, so this must not shell out.
const workingTreeContentHits: string[] = [];
function scanWorkingTreeContent(
  absoluteDirectory: string,
  relativeDirectory: string
): void {
  for (const entry of readdirSync(absoluteDirectory, { withFileTypes: true })) {
    const relativePath =
      relativeDirectory === "."
        ? entry.name
        : `${relativeDirectory}/${entry.name}`;
    if (entry.isDirectory()) {
      if (!generatedOrInstalledDirectoryNames.has(entry.name)) {
        scanWorkingTreeContent(
          join(absoluteDirectory, entry.name),
          relativePath
        );
      }
      continue;
    }
    if (!entry.isFile() || relativePath === "AGENTS.md") {
      continue;
    }
    const contents = readFileSync(join(absoluteDirectory, entry.name));
    if (contents.includes(0)) {
      continue; // binary
    }
    const text = contents.toString("utf8");
    if (retiredProviderContentRegex.test(text)) {
      const lineNumber = text
        .slice(0, text.search(retiredProviderContentRegex))
        .split("\n").length;
      workingTreeContentHits.push(`./${relativePath}:${lineNumber}`);
    }
  }
}
scanWorkingTreeContent(repoRoot, ".");
if (workingTreeContentHits.length > 0) {
  failures.push(
    `working tree content contains retired provider token:\n${workingTreeContentHits.join("\n")}`
  );
}

for (const relativePath of trackedFiles) {
  // Kit-generated doctrine file; exempt from content scanning (see generatedOrInstalledGlobExcludes).
  if (relativePath === "AGENTS.md") {
    continue;
  }
  if (relativePath.toLowerCase().includes(retiredProviderToken)) {
    failures.push(`${relativePath}: path contains retired provider token`);
    continue;
  }

  const absolutePath = join(repoRoot, relativePath);
  if (!statSync(absolutePath).isFile()) {
    continue;
  }

  const fileBytes = readFileSync(absolutePath);
  const fileContents = fileBytes.toString("utf8");
  if (fileContents.toLowerCase().includes(retiredProviderToken)) {
    failures.push(
      `${relativePath}: tracked content contains retired provider token`
    );
    continue;
  }
  if (retiredProviderContentRegex.test(fileContents)) {
    failures.push(
      `${relativePath}: tracked content contains retired provider residue`
    );
  }
}

for (const relativePath of activeGuidanceAndConfigPaths) {
  const absolutePath = join(repoRoot, relativePath);
  if (!existsSync(absolutePath)) {
    continue;
  }

  let fileContents = readFileSync(absolutePath, "utf8");
  for (const commandName of allowedRetiredProviderCommandNames) {
    fileContents = fileContents.replaceAll(commandName, "");
  }
  if (retiredProviderAliasRegex.test(fileContents)) {
    failures.push(
      `${relativePath}: active guidance/config/current plan contains retired provider alias`
    );
  }
}

for (const relativePath of activeVortexMirrorSchemaPaths) {
  const absolutePath = join(repoRoot, relativePath);
  if (!existsSync(absolutePath)) {
    failures.push(
      `${relativePath}: expected active Vortex mirror schema is missing`
    );
    continue;
  }

  const fileContents = readFileSync(absolutePath, "utf8");
  if (stalePaymentProviderMirrorRegex.test(fileContents)) {
    failures.push(
      `${relativePath}: active Vortex mirror schema uses stale payment provider wording`
    );
  }
  if (!fileContents.includes("Vortex Billing")) {
    failures.push(
      `${relativePath}: active Vortex mirror schema does not name Vortex Billing`
    );
  }
}

function scanWorkingTreePathNames(
  absoluteDirectory: string,
  relativeDirectory: string
): void {
  if (!existsSync(absoluteDirectory)) {
    return;
  }

  for (const entry of readdirSync(absoluteDirectory, { withFileTypes: true })) {
    if (
      entry.isDirectory() &&
      generatedOrInstalledDirectoryNames.has(entry.name)
    ) {
      continue;
    }

    const relativePath =
      relativeDirectory === "."
        ? entry.name
        : `${relativeDirectory}/${entry.name}`;
    if (relativePath.toLowerCase().includes(retiredProviderToken)) {
      failures.push(
        `${relativePath}: working tree path contains retired provider token`
      );
    }

    if (entry.isDirectory()) {
      scanWorkingTreePathNames(
        join(absoluteDirectory, entry.name),
        relativePath
      );
    }
  }
}

scanWorkingTreePathNames(repoRoot, ".");

if (failures.length > 0) {
  console.error("Retired provider residue proof failed:");
  for (const failure of failures) {
    console.error(`- ${failure}`);
  }
  process.exit(1);
}

console.log("Retired provider residue proof passed:");
console.log("- No tracked file paths contain the retired provider token.");
console.log("- No tracked file contents contain the retired provider token.");
console.log(
  "- No dependency graph package or owned working-tree path contains the retired provider token."
);
console.log(
  "- No owned source/config/doc content, including hidden env files and excluding generated/install/cache outputs, contains provider-shaped retired provider residue."
);
console.log(
  "- No active guidance/config/current plan file contains retired provider aliases outside approved proof command names."
);
console.log(
  "- Active Vortex mirror schemas name Vortex Billing as source of truth."
);
