export interface HttpRouteDefinition {
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly operationId: string;
  readonly summary: string;
}

export const httpRoutes: readonly HttpRouteDefinition[] = [
  {
    method: "POST",
    path: "/v1/billing/collect-invoice-payment",
    operationId: "collectInvoicePayment",
    summary: "Collect one billing invoice through the canonical payments workflow.",
  },
  {
    method: "POST",
    path: "/v1/billing/refund-invoice-payment",
    operationId: "refundInvoicePayment",
    summary: "Refund one billing invoice payment through the canonical payments workflow.",
  },
  {
    method: "POST",
    path: "/v1/billing/reconcile-invoice-payment",
    operationId: "reconcileInvoicePayment",
    summary: "Reconcile one billing invoice payment through the canonical payments workflow.",
  },
  {
    method: "POST",
    path: "/v1/billing/reconcile-invoice-refund",
    operationId: "reconcileInvoiceRefund",
    summary: "Reconcile one billing invoice refund through the canonical payments workflow.",
  },
  {
    method: "POST",
    path: "/v1/billing/merchant-readiness",
    operationId: "getMerchantReadiness",
    summary: "Return billing-facing merchant readiness state.",
  },
  {
    method: "POST",
    path: "/v1/billing/customer-payment-methods",
    operationId: "listCustomerPaymentMethods",
    summary: "Return billing-facing customer payment method summaries.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts",
    operationId: "listMerchantAccounts",
    summary: "List canonical merchant accounts for one tenant.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts",
    operationId: "createMerchantAccount",
    summary: "Create one canonical merchant account shell.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId",
    operationId: "getMerchantAccount",
    summary: "Return one canonical merchant account.",
  },
  {
    method: "PATCH",
    path: "/v1/merchant-accounts/:merchantAccountId",
    operationId: "updateMerchantAccount",
    summary: "Update one canonical merchant account.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/state",
    operationId: "getMerchantAccountState",
    summary: "Return canonical merchant readiness state.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/capabilities",
    operationId: "getMerchantAccountCapabilities",
    summary: "Return canonical merchant capability snapshots.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/timeline",
    operationId: "listMerchantTimeline",
    summary: "List canonical merchant timeline events.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/payout-profile",
    operationId: "getMerchantSellerPayoutProfile",
    summary: "Return the provider-backed seller payout profile snapshot for one merchant account.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/settlements",
    operationId: "listMerchantSettlements",
    summary: "List canonical settlements for one merchant account.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/settlements/:settlementId/payout-readiness",
    operationId: "getSettlementPayoutReadiness",
    summary: "Return seller payout readiness for one merchant settlement.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/settlements/:settlementId/funding-timeline",
    operationId: "getSettlementFundingTimeline",
    summary: "Return settlement and funding-transfer timeline for one merchant settlement.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/settlements/:settlementId",
    operationId: "getMerchantSettlement",
    summary: "Return one canonical settlement for one merchant account.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/payouts",
    operationId: "listMerchantPayouts",
    summary: "List canonical payouts for one merchant account.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/payouts/:payoutId",
    operationId: "getMerchantPayout",
    summary: "Return one canonical payout for one merchant account.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/disputes",
    operationId: "listMerchantDisputes",
    summary: "List canonical disputes for one merchant account.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/disputes/:disputeId",
    operationId: "getMerchantDispute",
    summary: "Return one canonical dispute for one merchant account.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/disputes/:disputeId/accept",
    operationId: "acceptDispute",
    summary: "Accept a dispute using the configured provider's native primitive.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/disputes/:disputeId/evidence",
    operationId: "listDisputeEvidence",
    summary: "List provider dispute evidence for one dispute.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/disputes/:disputeId/evidence",
    operationId: "createDisputeEvidence",
    summary: "Create provider dispute evidence for one dispute.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/disputes/:disputeId/evidence/submit",
    operationId: "submitDisputeEvidence",
    summary: "Submit provider dispute evidence for one dispute.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/disputes/:disputeId/adjustment-transfers",
    operationId: "listDisputeAdjustmentTransfers",
    summary: "List provider dispute adjustment transfers for one dispute.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/submit",
    operationId: "submitMerchantOnboarding",
    summary: "Submit merchant onboarding to the configured provider.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/:onboardingSessionId",
    operationId: "getMerchantOnboardingSnapshot",
    summary: "Return one canonical merchant onboarding session snapshot.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/:onboardingSessionId/refresh",
    operationId: "refreshMerchantOnboardingSession",
    summary: "Refresh one merchant onboarding session from provider state.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/:onboardingSessionId/links",
    operationId: "createMerchantOnboardingHostedLink",
    summary: "Create one tokenized Vortex-hosted merchant onboarding surface link.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/:onboardingSessionId/requirements",
    operationId: "listMerchantOnboardingRequirements",
    summary: "List canonical merchant onboarding requirements for one onboarding session.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/:onboardingSessionId/requirements/submit",
    operationId: "submitMerchantOnboardingRequirements",
    summary: "Submit canonical merchant onboarding requirement responses and document refs.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/:onboardingSessionId/requirements/:requirementId/upload-links",
    operationId: "createMerchantOnboardingRequirementUploadLink",
    summary: "Create a direct upload link for one onboarding requirement document.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/:onboardingSessionId/requirements/:requirementId/documents",
    operationId: "listMerchantOnboardingRequirementDocuments",
    summary: "List onboarding requirement document upload history.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/:onboardingSessionId/requirements/:requirementId/refresh",
    operationId: "refreshMerchantOnboardingRequirement",
    summary: "Refresh one onboarding requirement and its document statuses from provider state.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/onboarding/:onboardingSessionId/requirements/:requirementId/upload-status",
    operationId: "getMerchantOnboardingRequirementUploadStatus",
    summary: "Read latest onboarding requirement document upload status.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/customers",
    operationId: "createCustomerProfile",
    summary: "Create one merchant-scoped canonical customer profile.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/customers/:customerProfileId",
    operationId: "getCustomerProfile",
    summary: "Return one merchant-scoped canonical customer profile.",
  },
  {
    method: "PATCH",
    path: "/v1/merchant-accounts/:merchantAccountId/customers/:customerProfileId",
    operationId: "updateCustomerProfile",
    summary: "Update one merchant-scoped canonical customer profile.",
  },
  {
    method: "POST",
    path: "/v1/payment-method-setup-sessions",
    operationId: "createPaymentMethodSetupSession",
    summary: "Create a canonical payment method setup session for client tokenization/attach.",
  },
  {
    method: "POST",
    path: "/v1/payment-methods",
    operationId: "createPaymentMethod",
    summary: "Create one canonical payment method from an opaque setup token and setup session.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/customers/:customerProfileId/payment-methods",
    operationId: "listCustomerPaymentMethods",
    summary: "List canonical customer payment methods for a merchant-scoped customer profile.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/customers/:customerProfileId/payment-methods/:paymentMethodId",
    operationId: "getCustomerPaymentMethod",
    summary: "Return one canonical customer payment method for a merchant-scoped customer profile.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/customers/:customerProfileId/payment-methods/default",
    operationId: "setDefaultCustomerPaymentMethod",
    summary: "Set the canonical default payment method for a merchant-scoped customer profile.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/customers/:customerProfileId/payment-methods/:paymentMethodId/archive",
    operationId: "archiveCustomerPaymentMethod",
    summary: "Archive one canonical customer payment method.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/customers/:customerProfileId/payment-methods/:paymentMethodId/disable",
    operationId: "disableCustomerPaymentMethod",
    summary:
      "Disable one canonical customer payment method when it becomes unusable or provider-disabled.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/customers/:customerProfileId/payment-state",
    operationId: "getCustomerPaymentState",
    summary: "Return canonical customer payment readiness and default payment method state.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/terminal-locations",
    operationId: "listTerminalLocations",
    summary: "List canonical terminal locations for one merchant account.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/terminal-locations",
    operationId: "createTerminalLocation",
    summary: "Create one canonical terminal location for card-present payments.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/terminal-readers",
    operationId: "listTerminalReaders",
    summary: "List canonical terminal readers for one merchant account.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/terminal-readers/register",
    operationId: "registerTerminalReader",
    summary: "Register one canonical terminal reader.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/terminal-connection-sessions",
    operationId: "createTerminalConnectionSession",
    summary: "Create one terminal connection session for a POS client.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/card-present-payment-intents",
    operationId: "listCardPresentPaymentIntents",
    summary: "List canonical card-present payment intents for one merchant account.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/card-present-payment-intents",
    operationId: "createCardPresentPaymentIntent",
    summary: "Create one canonical card-present payment intent.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/card-present-payment-intents/:cardPresentPaymentIntentId",
    operationId: "getCardPresentPaymentIntent",
    summary: "Return one canonical card-present payment intent.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/card-present-payment-intents/:cardPresentPaymentIntentId/capture",
    operationId: "captureCardPresentPaymentIntent",
    summary: "Capture one authorized card-present payment intent.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/card-present-payment-intents/:cardPresentPaymentIntentId/cancel",
    operationId: "cancelCardPresentPaymentIntent",
    summary: "Cancel one open card-present payment intent.",
  },
  {
    method: "GET",
    path: "/v1/payment-hardware/skus",
    operationId: "listPaymentHardwareSkus",
    summary: "List Vortex Payments hardware SKUs for payment devices.",
  },
  {
    method: "POST",
    path: "/v1/payment-hardware/skus",
    operationId: "upsertPaymentHardwareSku",
    summary: "Create or update one Vortex Payments hardware SKU.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/payment-hardware/orders/preview",
    operationId: "previewPaymentHardwareOrder",
    summary: "Preview one Vortex Payments hardware order and provider action.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/payment-hardware/orders",
    operationId: "createPaymentHardwareOrder",
    summary: "Create one Vortex Payments hardware order.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/payment-hardware/orders",
    operationId: "listPaymentHardwareOrders",
    summary: "List Vortex Payments hardware orders.",
  },
  {
    method: "GET",
    path: "/v1/merchant-accounts/:merchantAccountId/payment-hardware/orders/:orderId",
    operationId: "getPaymentHardwareOrder",
    summary: "Get one Vortex Payments hardware order.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/payment-hardware/orders/:orderId/cancel",
    operationId: "cancelPaymentHardwareOrder",
    summary: "Cancel one Vortex Payments hardware order when still cancelable.",
  },
  {
    method: "POST",
    path: "/v1/merchant-accounts/:merchantAccountId/payment-hardware/orders/:orderId/returns",
    operationId: "requestPaymentHardwareReturn",
    summary: "Request a Vortex Payments hardware return.",
  },
  {
    method: "GET",
    path: "/v1/payment-intents",
    operationId: "listPaymentIntents",
    summary: "List canonical payment intents for one merchant scope.",
  },
  {
    method: "POST",
    path: "/v1/payment-intents",
    operationId: "createPaymentIntent",
    summary: "Create a canonical payment intent.",
  },
  {
    method: "GET",
    path: "/v1/payment-intents/:paymentIntentId",
    operationId: "getPaymentIntent",
    summary: "Return one canonical payment intent snapshot.",
  },
  {
    method: "POST",
    path: "/v1/payment-intents/:paymentIntentId/capture",
    operationId: "capturePaymentIntent",
    summary: "Capture one manual-authorization payment intent when provider semantics support it.",
  },
  {
    method: "POST",
    path: "/v1/payment-intents/:paymentIntentId/cancel",
    operationId: "cancelPaymentIntent",
    summary: "Cancel one manual-authorization payment intent when provider semantics support it.",
  },
  {
    method: "POST",
    path: "/v1/payment-intents/:paymentIntentId/retry",
    operationId: "retryPaymentIntent",
    summary: "Create one replacement payment intent from a failed or canceled payment intent.",
  },
  {
    method: "POST",
    path: "/webhooks/:provider",
    operationId: "ingestProviderWebhook",
    summary: "Receive and normalize a provider webhook payload.",
  },
] as const;
